### ISSUE TITLE
Display graph of coverage

### ISSUE THREAD

**Issue by everitt-andrew** [inTestiGator/pytest-deltacov#11]
# Description of the Issue
We need to take the information held by the XML file and format it in order to display the graph.

## Add Detailed Comment with More Information
We should probably use the matplotlib library to do this.

### Assigned Developers
@ALEXANDERB82

**Comment by ALEXANDERB82** [comment]
I will look into this but I will go forth using the [Seaborn Library](https://seaborn.pydata.org/).
